% Copyright 2018 Toyota Research Institute.  All rights reserved.
% 
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
% 
% The above copyright notice and this permission notice shall be included in
% all copies or substantial portions of the Software.
% 
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.

clc
close all
clear all
path1 = ['-I' fullfile(pwd,'../include')];
path2 = ['-I' fullfile(pwd,'../external')];
path3 = ['-I' fullfile(pwd,'../libgp/include')];
path4 = ['-I' fullfile(pwd,'../libgp_interface/include')];
path5 = ['-I' fullfile('/usr/include/eigen3')];

mex('-output', '../build/libgp_mex', 'COPTIMFLAGS="-Ofast"', path1, path2, path3, path4, path5,...
  '../src/libgpmex_interface.cc',...
  '../libgp/src/cov.cc',...
  '../libgp/src/cov_factory.cc',...
  '../libgp/src/cov_linear_ard.cc',...
  '../libgp/src/cov_linear_one.cc',...
  '../libgp/src/cov_matern3_iso.cc',...
  '../libgp/src/cov_matern5_iso.cc',...
  '../libgp/src/cov_noise.cc',...
  '../libgp/src/cov_rq_iso.cc',...
  '../libgp/src/cov_periodic_matern3_iso.cc',...
  '../libgp/src/cov_periodic.cc',...
  '../libgp/src/cov_se_ard.cc',...
  '../libgp/src/cov_se_iso.cc',...
  '../libgp/src/cov_sum.cc',...
  '../libgp/src/cov_prod.cc',...
  '../libgp/src/gp.cc',...
  '../libgp/src/gp_utils.cc',...
  '../libgp/src/sampleset.cc',...
  '../libgp/src/rprop.cc',...
  '../libgp/src/input_dim_filter.cc',...
  '../libgp/src/cg.cc',...
  '../libgp_interface/src/libgp_interface.cc');
